// /web/lib/agentRegistryAbi.ts
export const agentRegistryAbi = [
  {
    type: "function",
    name: "agents",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "metadataUri", type: "string" },
          { name: "active", type: "bool" },
          { name: "autoCreated", type: "bool" },
          { name: "totalWeightedRating", type: "uint128" },
          { name: "totalWeight", type: "uint128" },
          { name: "jobCount", type: "uint32" },
          { name: "feedbackCount", type: "uint32" },
          { name: "createdAt", type: "uint64" },
          { name: "lastUpdate", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "registerAgent",
    stateMutability: "nonpayable",
    inputs: [{ name: "metadataUri", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateAgent",
    stateMutability: "nonpayable",
    inputs: [{ name: "metadataUri", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "deactivateAgent",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setActive",
    stateMutability: "nonpayable",
    inputs: [{ name: "active", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "submitFeedback",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "bytes32" },
      { name: "rating", type: "uint8" },
      { name: "commentUri", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "registerJob",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "bytes32" },
      { name: "agent", type: "address" },
      { name: "client", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "jobs",
    stateMutability: "view",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "jobId", type: "bytes32" },
          { name: "client", type: "address" },
          { name: "agent", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "createdAt", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "feedbacks",
    stateMutability: "view",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "rating", type: "uint8" },
          { name: "commentUri", type: "string" },
          { name: "timestamp", type: "uint64" },
          { name: "client", type: "address" },
          { name: "agent", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getAvgRatingScaled",
    stateMutability: "view",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "AgentRegistered",
    inputs: [
      { name: "agent", type: "address", indexed: true },
      { name: "metadataUri", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentUpdated",
    inputs: [
      { name: "agent", type: "address", indexed: true },
      { name: "metadataUri", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentAutoCreated",
    inputs: [{ name: "agent", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentDeactivated",
    inputs: [{ name: "agent", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "JobRegistered",
    inputs: [
      { name: "jobId", type: "bytes32", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeedbackSubmitted",
    inputs: [
      { name: "jobId", type: "bytes32", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "rating", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
